### ISSUE TITLE
Why are we passing in numVals?

### ISSUE THREAD

**Issue by ebuchman** [joshkestenberg/t-logs#1]
https://github.com/joshkestenberg/t-logs/blob/b68f3345e40102237423d4d8da3c7a301c15a033/reader.go#L238

**Comment by ebuchman** [comment]
Same with newRound, checkBlock, checkVotes. Seems like there are unnecessary arguments?

**Comment by joshkestenberg** [comment]
numVals needs to be continually tracked/updated without being reset. all the "unique" arguments were extraneous though.. good eye. Fixed. Closing issue.

**Comment by ebuchman** [comment]
I don't understand - numVals isn't used in that function.

**Comment by joshkestenberg** [comment]
ln. 285 

`numVals, err = strconv.Atoi(stringVals)`

**Comment by ebuchman** [comment]
that's not using the value. you're just setting it. but its not a pointer. and then you just return that and overwrite numVals in the prior scope.

**Comment by joshkestenberg** [comment]
Actually it's now unnecessary. Before it was such that the function was called every pass, so if I were to redeclare it (in order to be able return it), it would be set to a default value of zero. Now the function is called on the condition that we'll be receiving a value for numVals.

**Comment by ebuchman** [comment]
Aha! Makes sense :)
