### ISSUE TITLE
New Feature: Communication intervals

### ISSUE THREAD

**Issue by ebuchman** [joshkestenberg/t-logs#3]
It would great to have a command that could tell us, at every interval X (eg. second, 10s, minute, etc.), which other nodes we are receiving messages from.

Output could be like:

0-10s:     X _ _ X _
10-20s:   X X_ X _
20-30s:   _ _ _ _ _
30-40s:   X _ _ X _

etc.

This would indicate that eg. between 20-30s, this node was likely partitioned off and not connected to anyone.

**Comment by joshkestenberg** [comment]
This is completed in another branch. Closed.
